--- 
title: "Jasonelle Documentation"
author: "Jasonelle Team"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
github-repo: jasonelle/jasonelle
url: 'http\://jasonelle.com'
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Jasonelle is a family of components that enables you creating apps and tools using only JSON."
geometry: "left=4cm, right=3cm, top=2.5cm, bottom=2.5cm"
fontsize: 12pt
linestretch: 1.5
toc-depth: 1
lof: False
lot: False
---

# Welcome

*Jasonelle* is an app framework that takes a JSON markup and turns it into Android/iOS 
native components and function calls, which then can be packaged and distributed as your own app. 
And the most important part: it's 100% open source under *MPL-2.0 license*,
which means you can take it and build your app, 
submit it to the App Store, and do whatever you want with it!.

## Main Goals

*Jasonelle* project want to reach these goals:

- Use known and popular technologies (*JSON*, *Javascript*). 💯
- Easy to learn, use and extend. ☺️
- Stable API. ⚓
- Use Native Components. 📱
- Great Documentation. 📝
- Friendly and Welcoming Community. 🤝
- A technology that could be used in 100 years. 🕰️

## Cool things about Jasonelle

- **100% NATIVE**: Jasonelle maps *JSON* into native 
components and native function calls. There is no gimmick. 
There is no magic.

- **App loads over HTTP (or local file)**: Your app exists 
100% as JSON, and loads from the cloud or local. 
No more hard-coding. Send Native App over HTTP Anything 
that can be expressed in JSON can be sent over the Internet. 
Anything that can be sent over the Internet doesn't need to be on the client. Since Jasonette lets you express the app 100% in JSON, you don't need to hard-code your app on the phone anymore. Instead, the app loads directly from the server everytime a user opens the app.

- **An app in 30 minutes**: No kidding, build an app in 30 minutes. 
Describe instead of programming. Instead of writing and compiling complex program lines, 
you only need to write a single markup that describes what the view should look like and 
how it should behave. An app that used to take days to build can be built in 30 minutes (or less).

- **Lowest possible learning curve**: No programming experience 
required. There's a small amount of things you need to know: 
JSON (And maybe a little JavaScript). Which means you can 
build an app without "becoming a programmer". 
Minimum learning curve You can describe the view 
layout (like HTML), component style (like CSS), and native 
function calls (like Javascript) **ALL in JSON**. 
All you need is a single JSON.

## Old Docs

The previous version of this documentation is present in the following url
[https://jasonelle.com/jasonette-old-docs/](https://jasonelle.com/jasonette-old-docs/).
The vast mayority of the old docs are still valid and useful.

## Examples

Plenty of code examples are stored in the [https://github.com/jasonelle/docs/tree/develop/examples/jasonette](https://github.com/jasonelle/docs/tree/develop/examples/jasonette) repository.

## Why JSON?

- Industry Standard, lightweight data-interchange format. 
Huge amount of programming languages and tools with support available.

- It is easy for humans to read and write. 
It is easy for machines to parse and generate. 

- A single plain text file can contain all the data and logic needed in a 
complete native app.

- You can use any backend to generate the app (or do not use a backend at all). 
Example: 
[Masonite](http://masoniteproject.com/), 
[ProcessWire](https://processwire.com/), 
[Express](https://expressjs.com/), 
[SailsJS](https://sailsjs.com/), 
[Laravel](https://laravel.com/), 
[Rails](https://rubyonrails.org/), 
[Flask](http://flask.pocoo.org/), 
[Django](https://www.djangoproject.com/), 
[AWS Lambda](https://aws.amazon.com/lambda/),
`file://` local file.

## Usable Apps in 100 years!

Thanks to *Jasonelle™️'s JSON technology* ️ you have all the tools
needed to create **agnostic** mobile apps. This means
if your app contains only static assets (audio, images, js, jsons, no server) 
and an interpreter exists in 100 years, your app will
be valid and usable!.

You can create mobile apps that stands the test of time, apps that
does not depends on *Apple* or *Google* ecosystems to be used.

Apps that can be used by the next generation of people, even after
you leave this dimension!.

More details here : 
[https://jasonelle.com/docs/discussions.html#apps-for-a-lifetime](https://jasonelle.com/docs/discussions.html#apps-for-a-lifetime).
